# Generated by Django 5.0.4 on 2024-05-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_room_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id_room',
        ),
    ]
