# Generated by Django 5.0.4 on 2024-05-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_room_id_room_id_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='id_room',
            new_name='room_id',
        ),
    ]
